 <html>

    <head>
       <title>Alterar cliente</title>
       <meta charset="utf-8">
       <link rel="shortcut icon" href="https://i.imgur.com/xtxyiN6.png.icon" />
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     <link rel="stylesheet" type="text/css" href="estilo2.css">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
   .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    } 


.navbar {
    margin-bottom: 0;
    background-color: #00CED1;
    z-index: 9999;
    border: 0;
    font-size: 12px !important;
    line-height: 1.42857143 !important;
    letter-spacing: 4px;
    border-radius: 0;
    font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
    color: #000000;
    
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
    color: #000000;
    background-color: #00CED1;
  }
  .navbar-default .navbar-toggle {
    border-color: #00CED1;
    color: #000000;
  }

   .form-floating {
          width: 500px;
          height: calc(1.5em + .75rem + 2px);
          margin-left: auto;
          margin-right: auto; 

        }

        .copyright{
          margin-bottom: 0;
          text-align: center;
        }

</style>
  
    </head>

    <body>
     
      <!-- BARRA DE NAVEGAÇÃO-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="https://i.imgur.com/xtxyiN6.png" alt="logo" style="width:40px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/menuPrincipal">Home</a>
            </li>
            <li class="nav-item">
          <a class="nav-link" href="/sobreNos">Quem somos</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/Receitas">Receitas</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/produtos">Cursos</a>
          </li>
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Registre-se
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/cadastro">Cadastre-se</a>
                <a class="dropdown-item" href="/login">Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquise aqui">
            <button class="btn btn-outline-primary-2 my-sm-0" type="submit" style="background-color: #00CED1;">Pesquisar</button>
          </form>
        </div>
    </nav>
    <!-- FIM BARRA DE NAVEGAÇÃO-->
     



 </div>
       <div class="container">
        <h2>Alterar Cliente</h2>
        <form action="/salvarCliente" method="post">
            <div class="form-group">
                <input type="hidden" class="form-control" id="Id" placeholder="Digite a id" name="id" value="<?php echo $this->view->dados[0]["id"] ?>">
            </div>
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="Nome" placeholder="Digite o nome do cliente" name="nome" value="<?php echo $this->view->dados[0]["nome"] ?>">
            </div>
           <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>

</body>
</html>
