<html>

	<head>
       <title>Cadastre-se</title>
       <meta charset="utf-8">
       <link rel="shortcut icon" href="https://i.imgur.com/xtxyiN6.png.icon" />
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     <link rel="stylesheet" type="text/css" href="estilo2.css">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
   .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    } 


.navbar {
    margin-bottom: 0;
    background-color: #00CED1;
    z-index: 9999;
    border: 0;
    font-size: 12px !important;
    line-height: 1.42857143 !important;
    letter-spacing: 4px;
    border-radius: 0;
    font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
    color: #000000;
    
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
    color: #000000;
    background-color: #00CED1;
  }
  .navbar-default .navbar-toggle {
    border-color: #00CED1;
    color: #000000;
  }

   .form-floating {
          width: 500px;
          height: calc(1.5em + .75rem + 2px);
          margin-left: auto;
          margin-right: auto; 

        }

        .copyright{
          margin-bottom: 0;
          text-align: center;
        }

</style>
  
	</head>

	<body>
     
      <!-- BARRA DE NAVEGAÇÃO-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="https://i.imgur.com/xtxyiN6.png" alt="logo" style="width:40px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/menuPrincipal">Home</a>
            </li>
            <li class="nav-item">
          <a class="nav-link" href="/sobreNos">Quem somos</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/Receitas">Receitas</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/produtos">Cursos</a>
          </li>
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Registre-se
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/cadastro">Cadastre-se</a>
                <a class="dropdown-item" href="/login">Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquise aqui">
            <button class="btn btn-outline-primary-2 my-sm-0" type="submit" style="background-color: #00CED1;">Pesquisar</button>
          </form>
        </div>
    </nav>
    <!-- FIM BARRA DE NAVEGAÇÃO-->
     


     <main class="form-signin">
     <form action="/salvarCliente" method="post">
        <h1 class="h3 mb-3 fw-normal" align="center">Página de Cadastro</h1>
        <div class="form-floating">
          <p>Nome: </p>
        <input type="text" class="form-control" placeholder="name" name="nome" required autofocus > </div>
        <br><br>
        <div class="form-floating">
          <p>E-mail: </p>
        <input type="email" class="form-control" placeholder="E-mail" name="email" required autofocus > </div>
        <br><br>
        <div class="form-floating">
          <p>Id: </p>
        <input type="id" class="form-control" placeholder="Id" name="id" required autofocus > </div>
        <br><br>
        
    <div class="form-floating">
  		<p>Cozinhas preferidas: </p>
  			<input type="checkbox" name="BR"> Brasileira<BR>
  			<input type="checkbox" name="AS"> Asiática<BR>
  			<input type="checkbox" name="FR"> Francesa<BR>
  			<input type="checkbox" name="IT"> Italiana<BR>
  			<input type="checkbox" name="MD"> Mediterrânea<BR>
  		<BR>
  		


  		<button class="btn btn-lg btn" type="submit" style="width: 200px; background-color:  #00CED1; color: #000000;border-color: #008080; margin-right: auto; margin-left: 20px;">Efetuar cadastro</button>
  		
      <button class="btn btn-lg btn" type="reset" style="width: 200px; background-color:  #00CED1; color: #000000; border-color: #008080;margin-right: 40px; margin-left: 20px;">Limpar</button>
    </div>
		<BR>
		<BR>
		<BR>
     </form>
    </main>
    <BR>
    <BR>
    <BR>
    <BR>
    <BR>
    <BR>

    <div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Ações</th>
          <th>Id</th>
          <th>Nome</th>
        </tr>
      </thead>
      <tbody>
        <?php
            foreach($this->view->dados as $indice => $cliente) {
              echo "<tr><td>
                  <a href='/alterarCliente?id=" . $cliente["id"] . "'>
                      <img src='imagens/Editar-icon.png' alt='Alterar' width='25' height='25'>
                  </a>

                  <a href='/excluirCliente?id=" . $cliente["id"] . "'>
                      <img src='imagens/Lixeira-icon.png' alt='Excluir' width='25' height='25'>
                  </a>

                   <a href='/incluirCliente?id=" . $cliente["id"] . "'>
                      <img src='imagens/Adicionar-icon.png' alt='Incluir' width='25' height='25'>
                  </a>
                  
                  </td><td>"
              . $cliente["id"] .
              "</td><td>"
              . $cliente["nome"] .
              "</td></tr>";
            }
        ?>
      </tbody>
    </table>
  </div>

  <footer class="container-fluid text-center">
      <p>Easy cooking © </p>
    </footer>

  
	</body>


</html>