<html>

  <head>

       <title>Home</title>
       <meta charset="utf-8">
       
       <link rel="shortcut icon" href="https://i.imgur.com/xtxyiN6.png.icon" />
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     <link rel="stylesheet" type="text/css" href="estilo2.css">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <style>
    .navbar {
        margin-bottom: 50px;
        border-radius: 0;
      } 

  .jumbotron{
        margin-bottom: 0;
        background-color: #FFFFFF;
      }

  .navbar {
      margin-bottom: 0;
      background-color: #00CED1;
      z-index: 9999;
      border: 0;
      font-size: 12px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
    }
    .navbar li a, .navbar .navbar-brand {
      color: #000000;
      
    }
    .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #000000;
      background-color: #00CED1;
    }
    .navbar-default .navbar-toggle {
      border-color: #00CED1;
      color: #000000;
    }

  </style>
  
 
  </head>

  <body>
      
      <!-- BARRA DE NAVEGAÇÃO-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="https://i.imgur.com/xtxyiN6.png" alt="logo" style="width:40px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/menuPrincipal">Home</a>
            </li>
            <li class="nav-item">
          <a class="nav-link" href="/sobreNos">Quem somos</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/Receitas">Receitas</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/produtos">Cursos</a>
          </li>
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Registre-se
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/cadastro">Cadastre-se</a>
                <a class="dropdown-item" href="/login">Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquise aqui">
            <button class="btn btn-outline-primary-2 my-sm-0" type="submit" style="background-color: #00CED1;">Pesquisar</button>
          </form>
        </div>
    </nav>
    <!-- FIM BARRA DE NAVEGAÇÃO-->

    <div class="jumbotron">
      <div class="container text-center">
        <h1>Easy Cooking</h1>      
        <p>Receitas, dicas e cursos culinários</p>
      </div>
    </div>

  

      
      <!-- CAIXA PARA LINKS DOS POSTS parte 1-->
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/179608-pipoca-de-leite-ninho.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2020/12/pipoca-de-leite-ninho-capa-392x261.jpg" class="rounded" alt="pipoca" width="304" height="236"> 
          </div>
          <div>
          <p>Pipoca de Leite Ninho</p>
          </div>
          </div>
        </div>
        </a>
        </div>
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/116712-almondegas-assadas-com-molho-de-tomate-e-vinho.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2020/11/1427252400000-Almondegas-assadas-392x261.jpg" class="rounded" alt="almondegas" width="304" height="236"> 
          </div>
          <div>
          <p>Almôndegas assadas</p>
          </div>
          </div>
        </div>
        </a>
        </div>
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/197412-bolo-de-chocolate-molhadinho-e-fofinho-com-calda-de-chocolate.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2019/11/bolo-2.jpg" class="rounded" alt="bolo" width="304" height="236"> 
          </div>
          <div>
          <p>Bolo de chocolate</p>
          </div>
          </div>
        </div>
        </a>
        </div>
      </div>
    </div>

    <!-- CAIXA PARA LINKS DOS POSTS parte 2-->
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/2114-omelete-rapido.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2020/11/omelete-fit-nutricao-392x261.jpg" class="rounded" alt="omelete" width="304" height="236"> 
          </div>
          <div>
          <p>Omelete simples</p>
          </div>
          </div>
        </div>
        </a>
        </div>
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/44422-caldo-de-peixe-pintado.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2020/02/receita-de-caldo-de-peixe-392x261.png" class="rounded" alt="caldo" width="304" height="236"> 
          </div>
          <div>
          <p>Caldo de Peixe</p>
          </div>
          </div>
        </div>
        </a>
        </div>
        <div class="col-sm">
          <a href="https://www.tudogostoso.com.br/receita/134285-biscoito-de-polvilho-assado-facil.html" target="_blank">
      <div class="p-3"> 
          <div style="display:inline-block;box-shadow: 7px 17px 12px #FFFFFF">
          <div>
          <img src="https://www.receitadahora.com/wp-content/uploads/2019/11/maxresdefault-7-392x261.jpg" class="rounded" alt="polvilho" width="304" height="236"> 
          </div>
          <div>
          <p>Biscoito de polvilho</p>
          </div>
          </div>
        </div>
        </a>
        </div>
      </div>
    </div>


<footer class="container-fluid text-center">
  <p>Easy cooking © </p>
</footer>
  </body>

</html>

