<html>

	<head>

    <title>Quem somos?</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="https://i.imgur.com/xtxyiN6.png.icon" />
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     <link rel="stylesheet" type="text/css" href="estilo2.css">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
   .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    } 


.navbar {
    margin-bottom: 0;
    background-color: #00CED1;
    z-index: 9999;
    border: 0;
    font-size: 12px !important;
    line-height: 1.42857143 !important;
    letter-spacing: 4px;
    border-radius: 0;
    font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
    color: #000000;
    
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
    color: #000000;
    background-color: #00CED1;
  }
  .navbar-default .navbar-toggle {
    border-color: #00CED1;
    color: #000000;
  }

</style>

  </head>

	<body>
    
   <!-- BARRA DE NAVEGAÇÃO-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="https://i.imgur.com/xtxyiN6.png" alt="logo" style="width:40px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/menuPrincipal">Home </a>
            </li>
            <li class="nav-item">
          <a class="nav-link" href="/sobreNos">Quem somos</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/Receitas">Receitas</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/produtos">Cursos</a>
          </li>
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Registre-se
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/cadastro">Cadastre-se</a>
                <a class="dropdown-item" href="/login">Login</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquise aqui">
            <button class="btn btn-outline-primary-2 my-sm-0" type="submit" style="background-color: #00CED1;">Pesquisar</button>
          </form>
        </div>
    </nav>
    <!-- FIM BARRA DE NAVEGAÇÃO-->
      <br>
      <br>
      <div class="container-fluid bg-grey">
      <div class="row">
        <div class="col-sm-4">
           <div class="imgTexto"><img class="ml-3"  src="https://i2.wp.com/spcity.com.br/wp-content/uploads/2017/03/carlino.jpg" width=400 height=300 alt="Mission" ></div>
        </div>
       
        <div class="col-sm-8">
          <h2>Quem é a Easy Cooking?</h2>
          <h5>Um pouco da nossa história, Abril 2, 2021</h5>
          <p>Estamos no mercado há alguns anos, tentando sempre o nosso melhor para fazer a diferença na vida dos nossos internautas e alunos.</p>
          <p>Atuando no ramo de cursos de gastronomia há mais de 10 anos, a Easy Cooking construiu uma plataforma online para facilitar o aprendizado dos apaixonados por culinária. Hoje temos mais de 100 cursos, contendo os mais variados tipos de cozinha, com chefes renomados de grandes escolas, inclusive internacionais, que serão seus mentores nesse tragetória culinarística.</p>
          <p>Temos o dever de oferecer a melhor experiência possível para nossos usuários! Estamos muito contentes em fazer parte da história de tantos brasileiros que conseguiram conquistar muitos novos horizontes através dos nossos cursos, ou até se tornaram empreendedores, confira algumas dessas histórias<a href="#"> aqui</a>.</p>
          <p>Você também é louco por gastronomia e gostaria de fazer parte do nosso time de easy cookers? Temos muitas vagas disponíveis, tanto para serviços internos, quanto para instrutores, para mais informações, acesse o link no <a href="#"> trabalhe conosco</a>.</p>
        </div>
      </div>
    </div>
    
    <div class="container-fluid bg-grey">
      <div class="row">
        <div class="col-sm-4">
           <div class="imgTexto"><img class="ml-3"  src="https://ideloblog.com.br/wp-content/uploads/2018/11/44089.jpg" width=400 height=300 alt="Mission" ></div>
        </div>
       
        <div class="col-sm-8">
          <h2>Nossos Valores</h2>
          <p>Missão: A nossa principal missão é entregar a melhor experiência e aprendizado possíveis para nossos alunos, respeitando o tempo de aprendizado de cada um, e auxiliando para que evoluam da melhor forma, aproveitando todas as trilhas de aprendizado que estiverem disponíveis, de forma eficiente e eficaz.</p>
          <p>Visão: A nossa visão é baseada não somente nas necessidades de mercado, mas também nas demandas dos nossos queridos usuários, por isso sempre estamos criando novos conteúdos para nossa comunidade, ouvindo sempre as opiniões daqueles que nos tornam únicos, vocês.</p>
        </div>
      </div>
    </div>
 

 <br>
<br>
    <footer class="container-fluid text-center">
  <p>Easy cooking © </p>
</footer>
  </body>
	</body>


</html>